### ISSUE TITLE
The directory does not exist

### ISSUE THREAD

**Issue by Arno-Ramon** [craft-snippets/Craft-modal-component#1]
After installing the plugin I can't acces any `./craft` commands.
When disabling the plugin it all works again.

<img width="1238" alt="Screenshot 2022-06-17 at 12 10 22" src="https://user-images.githubusercontent.com/97735915/174277934-970c4691-60da-4411-b6b6-680af46542dd.png">

PHP version | 8.1.3
OS version | Linux 5.10.104-linuxkit
Craft edition & version | Craft Solo 4.0.4
Database driver & version | MySQL 10.3.34
Modal component | 1.0.0

**Comment by piotrpog** [comment]
Thanks for reporting, fixed with latest update.
